apiVersion: v1
kind: Pod
metadata:
  labels:
    app: yscope-log-viewer-deployment
  name: yscope-log-viewer-deployment
spec:
  containers:
    - name: yscope-log-viewer-deployment
      image: amazon/aws-cli:latest
      command:
        - /bin/bash
        - -c
      args:
        - yum install -y tar gzip jq && curl -s https://raw.githubusercontent.com/y-scope/yscope-log-viewer/refs/heads/main/tools/deployment/k8s/s3/deploy.sh | bash
      env:
        - name: AWS_ENDPOINT_URL
          value: http://minio:9091
        - name: LOG_VIEWER_BUCKET
          value: log-viewer
        - name: TAG_NAME
          value: latest
      volumeMounts:
        - name: aws-credentials-volume
          mountPath: "/home/.aws"
      imagePullPolicy: IfNotPresent
  volumes:
    - name: aws-credentials-volume
      secret:
        secretName: aws-credentials
