apiVersion: v1
kind: Pod
metadata:
  name: deploy-yscope-log-viewer
spec:
  containers:
    # Dummy container which does nothing but sleep
    - name: dummy
      image: busybox
      command: [ "sh", "-c", "while true; do sleep 3600; done" ]
  initContainers:
    # Container which performs deployment once only
    # To inspect logs, use the following command; kubectl logs <pod> -c <container>
    - name: deploy-yscope-log-viewer
      image: amazon/aws-cli:latest
      command:
        - /bin/bash
        - -c
      args:
        - yum install -y gzip jq tar && curl -s https://raw.githubusercontent.com/y-scope/yscope-log-viewer/refs/heads/main/tools/deployment/k8s/s3/deploy.sh | bash
      env:
        - name: AWS_ENDPOINT_URL
          value: http://minio:9091
        - name: LOG_VIEWER_BUCKET
          value: log-viewer
        - name: LOG_VIEWER_RELEASE_TAG
          value: latest
      volumeMounts:
        - name: aws-credentials-volume
          mountPath: "/root/.aws"
      imagePullPolicy: IfNotPresent
  volumes:
    - name: aws-credentials-volume
      secret:
        secretName: aws-credentials
